# PyTorch Fundamentals Exercises

This notebook contains exercises based on the PyTorch Fundamentals tutorial. Each section corresponds to a topic from the original notebook. Complete the exercises by filling in the code cells where indicated.

## 1. Introduction to Tensors

### Exercise 1.1: Create a scalar tensor
Create a scalar tensor with the value 42 and print its value, number of dimensions (ndim), and shape.

In [1]:
import torch

# TODO: Create a scalar tensor
scalar = torch.tensor(42)

# Print details
print(scalar)
print(f"Number of dimensions: {scalar.ndim}")
print(f"Shape: {scalar.shape}")

tensor(42)
Number of dimensions: 0
Shape: torch.Size([])


### Exercise 1.2: Create a vector tensor
Create a vector tensor with values [1, 2, 3, 4] and print its value, ndim, and shape.

In [2]:
# TODO: Create a vector tensor
vector = torch.tensor([1,2,3,4])

# Print details
print(vector)
print(f"Number of dimensions: {vector.ndim}")
print(f"Shape: {vector.shape}")

tensor([1, 2, 3, 4])
Number of dimensions: 1
Shape: torch.Size([4])


### Exercise 1.3: Create a matrix tensor
Create a 2x3 matrix tensor with values [[1, 2, 3], [4, 5, 6]] and print its details.

In [3]:
# TODO: Create a matrix tensor
matrix = torch.tensor([[1,2,3],
                       [4,5,6]])

# Print details
print(matrix)
print(f"Number of dimensions: {matrix.ndim}")
print(f"Shape: {matrix.shape}")

tensor([[1, 2, 3],
        [4, 5, 6]])
Number of dimensions: 2
Shape: torch.Size([2, 3])


### Exercise 1.4: Create a 3D tensor
Create a tensor of shape (2, 2, 2) with sequential values from 1 to 8 using torch.arange and reshape.

In [5]:
# TODO: Create a 3D tensor
tensor_3d = tensor = torch.arange(1, 9)
tensor_3d = tensor.reshape(2, 2, 2)

# Print details
print(tensor_3d)
print(f"Number of dimensions: {tensor_3d.ndim}")
print(f"Shape: {tensor_3d.shape}")

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Number of dimensions: 3
Shape: torch.Size([2, 2, 2])


## 2. Random Tensors

### Exercise 2.1: Create a random tensor
Create a random tensor of shape (4, 4) and print it along with its dtype.

In [6]:
# TODO: Create random tensor
random_tensor = torch.rand(size=(4, 4))
random_tensor, random_tensor.dtype

print(random_tensor)
print(f"Datatype: {random_tensor.dtype}")

tensor([[0.9445, 0.3607, 0.4328, 0.9022],
        [0.0668, 0.5171, 0.2414, 0.0246],
        [0.9852, 0.7364, 0.1400, 0.2347],
        [0.1528, 0.0021, 0.2663, 0.8305]])
Datatype: torch.float32


### Exercise 2.2: Create an image-sized random tensor
Create a random tensor of shape (3, 224, 224) simulating an image (channels, height, width).

In [10]:
# TODO: Create image-sized random tensor
image_tensor = torch.rand(3, 224, 224)
print(f"Shape: {image_tensor.shape}")

Shape: torch.Size([3, 224, 224])


## 3. Zeros and Ones

### Exercise 3.1: Create a tensor of zeros
Create a tensor of zeros with shape (5, 5).

In [12]:
zeros_tensor = torch.zeros(5, 5)

print(zeros_tensor)
print(f"Shape: {zeros_tensor.shape}")

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
Shape: torch.Size([5, 5])


### Exercise 3.2: Create a tensor of ones like another tensor
Create a random tensor of shape (3, 3), then create a tensor of ones with the same shape using ones_like.

In [13]:
import torch
original_tensor = torch.rand(3, 3)
ones_tensor = torch.ones_like(original_tensor)

print("Original Random Tensor:")
print(original_tensor)

print("\nOnes Like Tensor:")
print(ones_tensor)

Original Random Tensor:
tensor([[0.0989, 0.0876, 0.9232],
        [0.2716, 0.5013, 0.6353],
        [0.0196, 0.3193, 0.7211]])

Ones Like Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


## 4. Creating Ranges

### Exercise 4.1: Create a range tensor
Create a tensor with values from 0 to 20 with a step of 2 using torch.arange.

In [14]:
# TODO: Create range tensor
range_tensor = torch.arange(start=0, end=20, step=2)
print(range_tensor)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])


## 5. Tensor Datatypes

### Exercise 5.1: Create tensors with specific dtypes
Create a tensor with values [1.0, 2.0, 3.0] using dtype=torch.float16 and another with dtype=torch.int64.

In [15]:
# TODO: float16 tensor
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)
# TODO: int64 tensor
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int64)
print(f"Float Tensor: {float_tensor} | Dtype: {float_tensor.dtype}")
print(f"Int Tensor: {int_tensor} | Dtype: {int_tensor.dtype}")

Float Tensor: tensor([1., 2., 3.], dtype=torch.float16) | Dtype: torch.float16
Int Tensor: tensor([1, 2, 3]) | Dtype: torch.int64


### Exercise 5.2: Change dtype
Convert the float16_tensor to float32.

In [16]:
# TODO: Change dtype
float16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)
float32_tensor = float16_tensor.to(torch.float32)

print(f"Original Dtype: {float16_tensor.dtype}")
print(f"New Dtype: {float32_tensor.dtype}")
print(f"Values: {float32_tensor}")

Original Dtype: torch.float16
New Dtype: torch.float32
Values: tensor([1., 2., 3.])


## 6. Getting Information from Tensors

### Exercise 6.1: Print tensor info
Create a random tensor of shape (2, 3, 4) and print its shape, dtype, and device.

In [17]:
# TODO: Create tensor and print info
data = torch.rand(2, 3, 4)
print(f"Shape:  {data.shape}")   # Or data.size()
print(f"Dtype:  {data.dtype}")
print(f"Device: {data.device}")

Shape:  torch.Size([2, 3, 4])
Dtype:  torch.float32
Device: cpu


## 7. Manipulating Tensors (Basic Operations)

### Exercise 7.1: Perform basic operations
Create a tensor [10, 20, 30]. Add 5, subtract 10, multiply by 2, and divide by 10.

In [18]:
tensor = torch.tensor([10, 20, 30])
# TODO: Add 5
added      = tensor + 5
# TODO: Subtract 10
subtracted = tensor - 10
# TODO: Multiply by 2
multiplied = tensor * 2
# TODO: Divide by 10
divided    = tensor / 10

print(f"Original:   {tensor}")
print(f"Add 5:      {added}")
print(f"Sub 10:     {subtracted}")
print(f"Mult by 2:  {multiplied}")
print(f"Div by 10:  {divided}")

Original:   tensor([10, 20, 30])
Add 5:      tensor([15, 25, 35])
Sub 10:     tensor([ 0, 10, 20])
Mult by 2:  tensor([20, 40, 60])
Div by 10:  tensor([1., 2., 3.])


### Exercise 7.2: Matrix multiplication
Create two tensors A (2x3) and B (3x2) with random values and perform matrix multiplication.

In [19]:
# TODO: Create A and B
A = torch.rand(2, 3)
B = torch.rand(3, 2)

# TODO: Matrix mul using torch.mm
result = A @ B

# TODO: Matrix mul using @
print(f"Matrix A (2x3):\n{A}")
print(f"\nMatrix B (3x2):\n{B}")
print(f"\nResult (2x2):\n{result}")

Matrix A (2x3):
tensor([[0.1681, 0.4986, 0.3966],
        [0.6122, 0.5114, 0.4594]])

Matrix B (3x2):
tensor([[0.4078, 0.9462],
        [0.6783, 0.1462],
        [0.6090, 0.1434]])

Result (2x2):
tensor([[0.6482, 0.2888],
        [0.8763, 0.7199]])


## 8. Tensor Aggregation

### Exercise 8.1: Find min, max, mean, sum
Create a tensor with values from 0 to 100 and find its min, max, mean, and sum.

In [20]:
data = torch.arange(0, 101, dtype=torch.float32)
tensor_min  = data.min()
tensor_max  = data.max()
tensor_mean = data.mean()
tensor_sum  = data.sum()

print(f"Min:  {tensor_min}")
print(f"Max:  {tensor_max}")
print(f"Mean: {tensor_mean}")
print(f"Sum:  {tensor_sum}")

Min:  0.0
Max:  100.0
Mean: 50.0
Sum:  5050.0


### Exercise 8.2: Argmin and argmax
Find the positions of the minimum and maximum values in the above tensor.

In [21]:

data = torch.arange(0, 101, dtype=torch.float32)
min_index = data.argmin()
max_index = data.argmax()

print(f"Index of Min: {min_index} (Value at this index: {data[min_index]})")
print(f"Index of Max: {max_index} (Value at this index: {data[max_index]})")

Index of Min: 0 (Value at this index: 0.0)
Index of Max: 100 (Value at this index: 100.0)


## 9. Reshaping, Stacking, Squeezing, Unsqueezing

### Exercise 9.1: Reshape a tensor
Create a tensor of shape (10,) and reshape it to (2, 5).

In [22]:

x = torch.arange(1, 11)
print(f"Original shape: {x.shape}")

reshaped_x = x.reshape(2, 5)

print("\nReshaped Tensor (2, 5):")
print(reshaped_x)
print(f"New shape: {reshaped_x.shape}")

Original shape: torch.Size([10])

Reshaped Tensor (2, 5):
tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
New shape: torch.Size([2, 5])


### Exercise 9.2: Stack tensors
Create two tensors of shape (2, 2) and stack them vertically and horizontally.

In [23]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4]])

tensor_B = torch.tensor([[5, 6],
                         [7, 8]])

stacked_v = torch.stack([tensor_A, tensor_B], dim=0)

stacked_h = torch.stack([tensor_A, tensor_B], dim=1)

print(f"Vertical Stack (dim=0):\n{stacked_v}")
print(f"Shape: {stacked_v.shape}")

print(f"\nHorizontal Stack (dim=1):\n{stacked_h}")
print(f"Shape: {stacked_h.shape}")

Vertical Stack (dim=0):
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Shape: torch.Size([2, 2, 2])

Horizontal Stack (dim=1):
tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])
Shape: torch.Size([2, 2, 2])


### Exercise 9.3: Squeeze and unsqueeze
Create a tensor of shape (1, 3, 1), squeeze it, then unsqueeze it back on dim=0.

In [24]:
x = torch.zeros(1, 3, 1)
print(f"Original shape: {x.shape}")

squeezed_x = x.squeeze()
print(f"Squeezed shape: {squeezed_x.shape}")

unsqueezed_x = squeezed_x.unsqueeze(dim=0)
print(f"Unsqueezed shape (dim=0): {unsqueezed_x.shape}")

Original shape: torch.Size([1, 3, 1])
Squeezed shape: torch.Size([3])
Unsqueezed shape (dim=0): torch.Size([1, 3])


### Exercise 9.4: Permute
Create an image tensor (3, 100, 100) and permute it to (100, 100, 3).

In [25]:
image_tensor = torch.rand(3, 100, 100)
print(f"Original shape: {image_tensor.shape}")

permuted_image = image_tensor.permute(1, 2, 0)

print(f"Permuted shape: {permuted_image.shape}")

Original shape: torch.Size([3, 100, 100])
Permuted shape: torch.Size([100, 100, 3])


## 10. Indexing

### Exercise 10.1: Index into a tensor
Create a tensor [[[1,2,3],[4,5,6],[7,8,9]]] and index to get 5, then the entire second row.

In [ ]:
index_tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
# TODO: Get 5

# TODO: Get second row [4,5,6]

## 11. PyTorch and NumPy

### Exercise 11.1: NumPy to PyTorch
Create a NumPy array [1,2,3,4] and convert it to a PyTorch tensor.

In [26]:
import torch
x = torch.tensor([[[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]]])

value_five = x[0, 1, 1]

second_row = x[0, 1, :]

print(f"Original Tensor Shape: {x.shape}")
print(f"Value 5: {value_five}")
print(f"Second Row: {second_row}")

Original Tensor Shape: torch.Size([1, 3, 3])
Value 5: 5
Second Row: tensor([4, 5, 6])


### Exercise 11.2: PyTorch to NumPy
Create a PyTorch tensor [5,6,7,8] and convert it to a NumPy array.

In [27]:
tensor_x = torch.tensor([5, 6, 7, 8])

numpy_array = tensor_x.numpy()

print(f"Tensor: {tensor_x} | Type: {type(tensor_x)}")
print(f"NumPy Array: {numpy_array} | Type: {type(numpy_array)}")

Tensor: tensor([5, 6, 7, 8]) | Type: <class 'torch.Tensor'>
NumPy Array: [5 6 7 8] | Type: <class 'numpy.ndarray'>


## 12. Reproducibility

### Exercise 12.1: Set manual seed
Set the manual seed to 77 and create two random tensors of shape (2,2). Check if they are equal.

In [28]:
torch.manual_seed(77)

tensor_A = torch.rand(2, 2)

tensor_B = torch.rand(2, 2)

are_equal = torch.equal(tensor_A, tensor_B)

print(f"Tensor A:\n{tensor_A}")
print(f"\nTensor B:\n{tensor_B}")
print(f"\nAre they equal? {are_equal}")

Tensor A:
tensor([[0.2919, 0.2857],
        [0.4021, 0.4645]])

Tensor B:
tensor([[0.9503, 0.2564],
        [0.6645, 0.8609]])

Are they equal? False


## 13. Running on GPUs

### Exercise 13.1: Check for GPU
Write code to check if CUDA is available and set the device accordingly.

In [29]:
import torch

gpu_available = torch.cuda.is_available()

device = "cuda" if torch.cuda.is_available() else "cpu"

print(f"Is CUDA available? {gpu_available}")
print(f"Current device being used: {device}")

x = torch.tensor([1, 2, 3]).to(device)
print(f"Tensor is on: {x.device}")

Is CUDA available? False
Current device being used: cpu
Tensor is on: cpu


### Exercise 13.2: Move tensor to GPU
Create a tensor and move it to the GPU if available. Then move it back to CPU and convert to NumPy.

In [30]:
device = "cuda" if torch.cuda.is_available() else "cpu"

x = torch.tensor([1.0, 2.0, 3.0])
print(f"Initial device: {x.device}")

x_on_gpu = x.to(device)
print(f"Moved to: {x_on_gpu.device}")

final_array = x_on_gpu.cpu().numpy()

print(f"Final object type: {type(final_array)}")
print(f"Final values: {final_array}")

Initial device: cpu
Moved to: cpu
Final object type: <class 'numpy.ndarray'>
Final values: [1. 2. 3.]
